name: Static Splash-Page Template
author: Andy Brown
description: This is the Site Description....

# Social Media Accounts
facebook: AccountName
twitter: AccountName
instagram: AccountName
vimeo:
snapchat:
tumblr:
behance:
deviantart:
soundcloud:
spotify:
googleplus:
pinterest:
youtube:
githubprofile:
linkedin:
email: mail@email.com