name: Static Site Template

# Social Media Accounts
facebook: AccountName
twitter: AccountName
instagram: AccountName
vimeo:
snapchat:
tumblr:
behance:
deviantart:
soundcloud:
spotify:
googleplus:
pinterest:
youtube:
githubprofile:
linkedin:
email: mail@email.com